version: 0.2

env:
  parameter-store:
    ECR_URI: /Samson/ECR/repo

phases:
  install:
    commands:
      - echo Installing Terraform...
      - yum install -y yum-utils
      - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - yum -y install terraform

  pre_build:
    commands:
      - echo Logging into ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $ECR_URI
      - COMMIT_ID=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-10)
      - BUGGY_APP="${ECR_URI}:${COMMIT_ID}"
      - echo "$BUGGY_APP" > image_tag.txt
      - echo "Image $BUGGY_APP"
      - echo Downloading tfvars from S3...
      - aws s3 cp s3://buggyapp-statefile-samson/env/dev/terraform.tfvars terraform.tfvars

  build:
    commands:
      - echo Building Docker image...
      - BUGGY_APP=$(cat image_tag.txt)
      - docker build -f Dockerfile.app -t $BUGGY_APP .
      - echo Docker image built successfully.

  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - BUGGY_APP=$(cat image_tag.txt)
      - docker push $BUGGY_APP
      - echo Docker image pushed successfully.
      - echo Creating imagedefinitions.json for ECS...
      - printf '[{"name":"buggy-web","imageUri":"%s"}]' "$BUGGY_APP" > imagedefinitions.json
      - echo Copying tfvars to CI-CD folder...
      - cp terraform.tfvars CI-CD/
      - echo Running terraform apply in CICD folder...
      - cd CI-CD
      - terraform init -backend-config=backend.hcl
      - terraform apply --auto-approve -var="image=$BUGGY_APP" -var-file=terraform.tfvars

artifacts:
  files:
    - imagedefinitions.json
