version: 0.2
 
env:
  parameter-store:
    ECR_URI: /Samson/ECR/repo
 
phases:
  pre_build:
    commands:
      - echo Logging into ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $ECR_URI
      - COMMIT_ID=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-10)
      - BUGGY_APP="${ECR_URI}:${COMMIT_ID}"
 
  build:
    commands:
      - echo Building Docker image...
      - echo "$BUGGY_APP"
      - docker build -f Dockerfile.app -t $BUGGY_APP .
      - echo Docker image built successfully.
 
  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push $BUGGY_APP
      - echo Docker image pushed successfully.
      - echo Creating imagedefinitions.json for ECS...
      - printf '[{"name":"buggy-web","imageUri":"%s"}]' "$IMAGE_TAG" > imagedefinitions.json
      - cat imagedefinitions.json
 
artifacts:
  files:
    - imagedefinitions.json
