FROM ruby:3.3.8

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Kolkata

# Install system packages and MySQL dependencies
RUN apt-get update -qq && apt-get install -y \
    nodejs \
    default-mysql-client \
    default-libmysqlclient-dev \
    build-essential \
    tzdata \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
