default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  username: <%= ENV['DB_USERNAME'] || 'samson1' %>
  password: <%= ENV['DB_PASSWORD'] || 'samson123' %>
  host: <%= ENV['DB_HOST'] || 'localhost' %>

development:
  <<: *default
  database: <%= ENV['DB_NAME'] || 'myapp_development' %>

production:
  <<: *default
  database: <%= ENV['DB_NAME'] || 'myapp_production' %>
